### ISSUE TITLE
Help Me Sir

### ISSUE THREAD

**Issue by MRH-XD** [zaidrao/Facebook-Lite-Plus#2]
Hey Sir, 

I have maked my own facebook lite + apk but I don't what is code of cookie login feature. Please can you told me the code of cookie login feature? If you want to help me in this problem then please send me the code in your reply.
Thank you Sir.

**Comment by devilkingofficial** [comment]
![Screenshot_2023-09-14-07-07-53-92_3c3878a44733fc39cd8cce94d7e29e0f](https://github.com/zaidrao/Facebook-Lite-Plus/assets/141665912/044159da-aa8e-4612-bd9a-bd3870a8cece)

**Comment by R4BB1Y** [comment]
Vai asena fb lite plus kaj kore na
