### ISSUE TITLE
Cant install app

### ISSUE THREAD

**Issue by BlazingKnightBD** [zaidrao/Facebook-Lite-Plus#3]
![Screenshot_2023-07-26-13-14-44-011_com google android packageinstaller-edit](https://github.com/zaidrao/Facebook-Lite-Plus/assets/137974692/0c61b93f-cf40-4664-bb7c-3539a804cb9a)

**Comment by MRSKING404** [comment]
Not awllou

**Comment by zaidrao** [comment]
fix
