### ISSUE TITLE
Your are using modified version of app, please use original one.

### ISSUE THREAD

**Issue by neomkrd** [zaidrao/Facebook-Lite-Plus#5]
![Screenshot_2023-10-09-13-30-25-698_com rao liteplus-edit](https://github.com/zaidrao/Facebook-Lite-Plus/assets/73109606/a984b4e7-de49-4357-a20e-2067b5c765fc)

**Comment by joyarifsikdar** [comment]
> ![Screenshot_2023-10-09-13-30-25-698_com rao liteplus-edit](https://user-images.githubusercontent.com/73109606/273560211-a984b4e7-de49-4357-a20e-2067b5c765fc.jpg)

**Comment by zaidrao** [comment]
fixed

**Comment by neomkrd** [comment]
Thank you 😊
